### ISSUE TITLE
For some reason, the GOTO, LOOKAT commands do not work

### ISSUE THREAD

**Issue by MisingN** [MakkusuOtaku/minegpt#2]
For some reason, the commands do not work, I write to the GOTO bot and the coordinates of the place, it writes that it goes there, but does not do it, it is the same with other commands, I did not make any changes to the code, please help

**Comment by MakkusuOtaku** [comment]
By default the bot responds to messages in "conversation" mode. To make it follow instructions you should start your message with an exclamation mark.

For example:
!look at me
