### ISSUE TITLE
I'm looking to collaborate…

### ISSUE THREAD

**Issue by SonicandTailsCD** [MakkusuOtaku/minegpt#3]
Hello! This isn't really an issue, but I was wondering if you authorize collaboration, such as pull requests/collaborators… I don't have a specific free time period, I'd just upload code whenever I'm available. Is this okay? Please reach out. :)
(I'm not asking for write permission, you may give it if you'd like, but this question's referring to pull requests. :) )

**Comment by MakkusuOtaku** [comment]
Thanks but I'm not looking to collaborate so I'll have to decline.

**Comment by SonicandTailsCD** [comment]
> Thanks but I'm not looking to collaborate so I'll have to decline.

It's okay, thanks anyway :)
